title: Ein Titel für die Webseite
author: André Alexander Bell
email: andre.bell@wago.com
remote_theme: andrebell/jekyll-TeXt-theme
lang: de
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-relative-links
